### ISSUE TITLE
Rename the SafeInfo endpoint

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-client-gateway#1142]
## Summary
A minor nice-to-have improvement for the SafeInfo endpoint.
It would make it easier to debug CGW requests if that endpoint had a distinct "name", e.g. `/safe-info`:
<img width="604" alt="Screenshot 2024-02-14 at 08 42 13" src="https://github.com/safe-global/safe-client-gateway/assets/381895/1b6bc0ec-22bd-4280-9bd8-15335d114157">

## Requirements

Add a "name" to the Safe Info endpoint, i.e. another path segment in the pathname, like `safe-info`, _after_ the address parameter.

E.g.:
```
https://safe-client.safe.global/v1/chains/1/safes/0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6
```
->
```
https://safe-client.safe.global/v1/chains/1/safes/0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6/info
```

**Comment by fmrsabino** [comment]
This does not sound REST-like with the current model that we have.

With `/v1/chains/1/safes/<address>` you are accessing a unique resource under `safes` (i.e.: you can expect one and only one resource which is identified by `address`).

With `/v1/chains/1/safe-info?address=<address>` it hints that we have one resource (`safe-info`) and that you filter that resource. It can then create the wrong expectations on the client side:
- The endpoint can return multiple safe infos if not filtered (not correct).
- The wrong filter might return an empty collection.
- Query parameters are usually seen as optional as a way to filter components of said resource.

We should not change the structure of the API because of how it's listed in a debugger/console (as this can potentially be configured on the said tool to show more information).

**Comment by katspaugh** [comment]
True, let me edit the description.

**Comment by fmrsabino** [comment]
> > We should not change the structure of the API because of how it's listed in a debugger/console (as this can potentially be configured on the said tool to show more information).
> 
> As an open source and a public good project, I think it's important to have a good developer experience.

I agree that it's important to have a good developer experience. Changing the API specification therefore should follow what is expected on each resource. 

Not showing the full path on one tool (other developers might use different tools) should not be the only reason to change a public API (or even a private one) though. Therefore, and as aligned internally with team, we won't be working on this issue/request. 

For Chrome Dev Tools you can enable "big request rows" – https://developer.chrome.com/docs/devtools/network/reference#request-rows
