### ISSUE TITLE
Try to fetch Safe App information from config service first

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-client-gateway#855]
**Is your feature request related to a problem? Please describe.**
Currently the client gateway only looks for the manifest.json of a Safe app based on the Safe app url provided in the `origin` field.

**Describe the solution you'd like**
We should first check the config service if it has information about an origin and then fallback to other sources (e.g. manifest)

**Describe alternatives you've considered**
We should remove this information from the config service completely and only rely on the manifest in all places (e.g. Safe Apps list endpoint)

**Additional context**
- https://github.com/safe-global/safe-client-gateway/blob/main/src/providers/info.rs#L152-L168
- https://app.gitbook.com/o/-MhyDtGxUyODu7d4sgda/s/-MhyEZtd5TVytPJtyS7v-2910905616/~/diff/~/changes/2sfEFsdfUrv0lFHiCLOO/build/sdks/safe-apps/releasing-your-safe-app
- https://gnosisinc.slack.com/archives/C01GL8X8L3H/p1650546491443809

**Comment by fmrsabino** [comment]
> We should first check the config service if it has information about an origin and then fallback to other sources (e.g. manifest)

Regarding format, it seems that we don't have it stored in a consistent manner. For some apps the `origin` is a JSON representation, for other it is a URL and for others just a String.

This makes it querying the Safe Config Service a bit more tricky – which format shall we consider?

The Safe Client Gateway seems to try to parse it as JSON: https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/transactions/converters/safe_app_info.rs but this is not correct for all the cases

**Comment by fmrsabino** [comment]
> > We should first check the config service if it has information about an origin and then fallback to other sources (e.g. manifest)
> 
> Regarding format, it seems that we don't have it stored in a consistent manner. For some apps the `origin` is a JSON representation, for other it is a URL and for others just a String.
> 
> This makes it querying the Safe Config Service a bit more tricky – which format shall we consider?
> 
> The Safe Client Gateway seems to try to parse it as JSON: https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/transactions/converters/safe_app_info.rs but this is not correct for all the cases

After clarifying internally we are assuming that the query to the Safe Config Service should involve just a URL (no JSON and no non-url Strings).

The Safe Client Gateway then can query this endpoint after validating the data on the CGW side.

**Comment by fmrsabino** [comment]
One issue that I see with querying the `safe-config-service` with a specific `url` is that a url can point to the same location with multiple representations. Eg.:

- `https://cloudflare-ipfs.com/ipfs/QmT96aES2YA9BssByc6DVizQDkofmKRErs8gJyqWipjyS8`
- `https://cloudflare-ipfs.com/ipfs/QmT96aES2YA9BssByc6DVizQDkofmKRErs8gJyqWipjyS8/` (trailing slash)
- `https://cloudflare-ipfs.com:<PORT>/ipfs/QmT96aES2YA9BssByc6DVizQDkofmKRErs8gJyqWipjyS8`

Querying with the `url` might result in no entries even though a Safe App exists with that URL.

We can think about alternatives like formatting the URL but overall I don't think it's exactly a scalable solution because it's not exactly an `id`.
