### ISSUE TITLE
Tx history table - Date labels can be wrong in some timezones

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-client-gateway#924]
## Bug description
When there is no filter applied, the date label that groups tx in table is 1 day off from the date of the tx; A tx created.
It might have to do with the timezone. This was tested in the GMT -3.00

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Go to this safe that has a bunch of tx's https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/history
 2. Search for the tx on Sept 6 (the label in the table)
 3. Hover the date in the tx

## Expected result
It should also be at some time of the day on the sept 6

## Obtained result
The tx are on Sept 7. 

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/189559731-4166685e-2352-4905-8d98-f1eca9458f9f.png)

NOTE:
There is a case where the date in the tx and the label in the history is fine, I assume because the tx was done near midnight:
![image](https://user-images.githubusercontent.com/4503659/189559783-c00a1fd9-c9c6-4bab-834e-5f3cdd3f0045.png)

**Comment by katspaugh** [comment]
I've made another issue to remove the client-side date conversion and send the param to the backend: https://github.com/safe-global/safe-wallet-web/issues/3001

**Comment by fmrsabino** [comment]
Closing. Further updates on the ticket mentioned in. https://github.com/safe-global/safe-client-gateway/issues/924#issuecomment-1852030303

**Comment by katspaugh** [comment]
@fmrsabino when I pass timezone_offset to the backend, the grouping by date becomes consistent, but the timestamps aren all shifted according the offset, so I'd have to shift them back. I think this is not correct. Timestamps should always be in UTC.

**Comment by fmrsabino** [comment]
> @fmrsabino when I pass timezone_offset to the backend, the grouping by date becomes consistent, but the timestamps are all shifted according the offset, so I'd have to shift them back in the frontend code. I think this is not correct. Timestamps should always be in UTC.

The goal of `timezone_offset` is to shift all the available timestamps with the offset so that not only the grouping works but is consistent with the transactions that it contains.

> Timestamps should always be in UTC.

I don't think this is correct (at least on the API level given the query parameter to shift the timezone) but if the user wants UTC then there's no need to use `timezone_offset` because that would be the default.

**Comment by katspaugh** [comment]
Timestamps in their current numerical form must be in UTC, as it's their defintion: https://www.unixtimestamp.com
They do not and cannot contain the timezone information.

If we do want to send all timestamps in a specified timezone, they should be in another format, e.g. an ISO string like `2024-01-08T10:06:40+02:00` which encodes the timezone and lets JS correctly parse and format a Date object.

With the current backend response, we cannot just take a numeric timestamp and pass it to `new Date()`, as it will automatically adds the local timezone offset. If you shift these timestamps on the backend, the only way to undo it on the client would be to manually subtract the timezone offset everywhere where a date is displayed. It's as messy as it sounds.

So I think it's good that the backend takes a timezone_offset parameter, as it helps correctly group txs by date, but it shoudn't use that to shift UTC timestamps.

**Comment by fmrsabino** [comment]
> Timestamps in their current numerical form must be in UTC, as it's their defintion: https://www.unixtimestamp.com They do not and cannot contain the timezone information.

I'm aware. The issue is that there was a mismatch between how we interpret the Date headers vs the timestamps of the transactions.

> If we do want to send all timestamps in a specified timezone, they should be in another format, e.g. an ISO string like `2024-01-08T10:06:40+02:00` which encodes the timezone and lets JS correctly parse and format a Date object.

While I agree with this change it's a change on the API level that we should pursue on future iterations as I'd say the timestamp field should be replaced in that case. But we can open the discussion then if we get to that point.

> With the current backend response with shifted timestamps, we cannot just take a numeric timestamp and pass it to `new Date()`, as it will automatically add the local timezone offset. If you shift these timestamps on the backend, the only way to undo it on the client would be to manually subtract the timezone offset everywhere where a date is displayed. It's as messy as it sounds.

Yes this is messy. The goal was to use the timestamp as it is without any timezone conversion as that would be tackled by the CGW.

> So I think it's good that the backend takes a timezone_offset parameter, as it helps correctly group txs by date, but it shoudn't use that to shift UTC timestamps.

I agree. @DmitryBespalov we should check how this change affects mobile. From the discussion:
- `timezone_offset` should be used for grouping **only**
- Timezone conversion is done on the client side.

**Comment by DmitryBespalov** [comment]
@fmrsabino what was the reason this timestamp adjustment was introduced in the first place? Rust client didn't adjust timestamps, but just used them for grouping - that's what we had before.

**Comment by fmrsabino** [comment]
> @fmrsabino what was the reason this timestamp adjustment was introduced in the first place? Rust client didn't adjust timestamps, but just used them for grouping - that's what we had before.

There was an issue where the Date headers were taking into consideration the timezone offset but not the transactions under each group. This led to some inconsistencies that were reported multiple times.

There was also this (wrong) assumption that the clients would render the dates as is (no further timezone conversions). While this can work, it can lead to some confusion on what the timestamp returned actually represents as mentioned in https://github.com/safe-global/safe-client-gateway/issues/924#issuecomment-1880705387.

My suggestion: revert the `timezone_offset` changes and make sure that the date headers are returned in UTC so that any UNIX timestamp can and should be considered as UTC.

I will also add this to the documentation of the route so that it's more clear in the future.

> Obviously, this change back to the original implementation affects mobile, too - I'll need to release new version. But, this is a minor thing and is easy to do

Yes I do understand this. Apologies for this back and forth. It was not clear on where the timezone conversion should be and I agree that given a UNIX timestamp it should be treated as a UTC (which was partially not respected in the CGW with the headers).

If we have an agreement on this: "Every UNIX timestamp should be considered as UTC" then I'd go ahead and implement these changes on the CGW side.

**Comment by DmitryBespalov** [comment]
Let's do it

**Comment by fmrsabino** [comment]
@DmitryBespalov @katspaugh there's another side effect to this change: the `DATE_LABEL` were previously reset to the start of the day (hours, minutes, seconds, set to 0).

However if we consider that every timestamp returned in `/history` endpoint follows the UTC timezone it'd be "messy" for the client side to know if the timezone offset changed the day or not.

Example: Transaction History with 2 transactions.

TX1: Sun Dec 31 2023 22:12:55 GMT+0000
TX2: Sun Dec 31 2023 23:12:55 GMT+0000

Without the `timezone_offset` (output sorted):
1. Date Label = Dec 31 2023
2. TX2
3. TX1

With the `timezone_offset` set to +1 hour:
1. Date Label = Jan 01 2024
2. TX2
3. Date Label = Dec 31 2023
4. TX1

However if we do follow the assumption that every timestamp returned is in UTC:
1. Date Label = Dec 31 2023
2. TX2
3. Date Label = Dec 31 2023
4. TX1

Following up the proposal of every timestamp in UTC, the Date Labels should also have the full time information. Therefore when the time conversion happens on the client side you'd correctly shift one of the labels to "Jan 01 2024" and the other one remains with "Dec 31 2023".

Thoughts?

**Comment by DmitryBespalov** [comment]
that's exactly how it worked: we get unix timestamp, add locale information (incl. time zone), and it's displayed correctly as different dates.

**Comment by fmrsabino** [comment]
> that's exactly how it worked: we get unix timestamp, add locale information (incl. time zone), and it's displayed correctly as different dates.

Yes 👍 My point was more to underline the fact that this change will affect the Date Labels in such a way that instead of getting the timestamp of the date label set to midnight (00:00:00) you'd get the full time information of the transaction of that group.

On the client side the timezone should still be applied but then only the day should be rendered.

**Comment by katspaugh** [comment]
Yes, it makes sense for date labels to not be at midnight but mirror the first (or last?) timestamp of the group.

**Comment by fmrsabino** [comment]
We have discovered that this issue was partially solved – daylight savings are still not taken into consideration. I've opened an [issue](https://github.com/safe-global/safe-client-gateway/issues/1024) with more details.

**Comment by DmitryBespalov** [comment]
Researching the UTC and DST (daylight saving time), it seems that the best way to resolved the issue with DST is to use the `timezone ID`, like `Europe/Paris` instead of the `timezone_offset` (`+1:00`). This way, backend gets full information about the timezone from the clients, including the DST adjustment. If the timezone ID is not available then we can fall back to the timezone offset.

References:
https://tc39.es/proposal-temporal/docs/ambiguity.html#understanding-time-zones-offset-changes-and-dst
https://tc39.es/proposal-temporal/docs/ambiguity.html#ambiguity-due-to-dst-or-other-time-zone-offset-changes
