### ISSUE TITLE
/v1/balances/supported-fiat-codes err

### ISSUE THREAD

**Issue by masayil** [safe-global/safe-client-gateway#948]
I set up the **gnosis safe** on a private network.
gateway api err:
`curl http://120.133.222.74:9090/v1/balances/supported-fiat-codes`
{"code":1337,"message":"Unknown 'Exchange' json structure"}
Exchange rate API setting:
![image](https://user-images.githubusercontent.com/65291464/183793809-d1cd0634-f16b-4cd2-9629-d73f92546519.png)

![image](https://user-images.githubusercontent.com/65291464/183649309-5f28db7f-b117-4573-8dd5-8c7ab802d34a.png)
![image](https://user-images.githubusercontent.com/65291464/183793963-9dac65f3-47ee-4df9-aceb-960df1e78f37.png)

Is this error normal on private network?

**Comment by moisses89** [comment]
@masayil  could you provide more information? 
For example: api.exchangeratesapi is working for you? if yes, share the response body.

**Comment by moisses89** [comment]
This question is related with exchangesratesapi here you can find the documentation https://exchangeratesapi.io/documentation/

**Comment by masayil** [comment]
Hi.  I change the default URL. I use `https://api.apilayer.com/exchangerates_data/latest` and get the result.

**Comment by masayil** [comment]
But the web cannot access the api - /v1/balances/supported-fiat-codes
![image](https://user-images.githubusercontent.com/65291464/184144314-a4954f74-16df-49aa-97ec-7d5bc5112a49.png)
![image](https://user-images.githubusercontent.com/65291464/184144389-ecc4c1c9-a626-47ca-9823-9cd7bfb6546e.png)

**Comment by fmrsabino** [comment]
@masayil you leaked your API key here: https://github.com/safe-global/safe-client-gateway/issues/948#issuecomment-1211988255

Please consider changing it.

**Also you have been opening multiple issues around the same topic:**
- https://github.com/safe-global/safe-client-gateway/issues/943
- https://github.com/safe-global/safe-client-gateway/issues/944
- https://github.com/safe-global/safe-client-gateway/issues/948 (this one).

Please do not do that. Additionally it'd be better if you don't comment with just images and then update the comments on a later stage. It makes it hard for use to understand and follow what the issue is.

**Comment by praveensyner** [comment]
Hi @masayil , May I know what is the fix here. How did the issue got resolved.
